### ISSUE TITLE
stopped working after upgrade to IntelliJ 2020.3 (build 203.5981) 

### ISSUE THREAD

**Issue by Fontyschriek** [Hazem-Ben-Khalfallah/test-cherry#1]
planned to use it in new semester for our students, but they will definitely use the latest version of intellij. Now they cannot use it anymore.

**Comment by Hazem-Ben-Khalfallah** [comment]
@Fontyschriek I just uploaded a fix that makes the plugin compatible with Intellij 2020.3 version.

**Comment by Hazem-Ben-Khalfallah** [comment]
version **3.2** is now available on Intellij plugins marketplace. I'm going to close this issue.

**Comment by Fontyschriek** [comment]
Thanks for the swift update!

kind regards,
                erik v.d. Schriek
