### ISSUE TITLE
Can you update TestCherry for intelliJ 2022 versions?

### ISSUE THREAD

**Issue by Fontyschriek** [Hazem-Ben-Khalfallah/test-cherry#22]
My students now need to download the 2021 versions of intelliJ, which becomes increasingly difficult with dependencies on newer plugins for the 2022 intelliJ version. 
Can you tell if a new version can be created?
many thanks in advance.

**Comment by Fontyschriek** [comment]
anything I can contribute to speed this up ( I don't have experience with IntelliJ plugin development)? I need TestCherry in about 5 weeks for my students to work with IntelliJ 2022 versions.

**Comment by Hazem-Ben-Khalfallah** [comment]
Hi @Fontyschriek , sorry for not being able to upgrade the plugin lately because I'm working on other projects :pray: . I'll try to make some time to fix it before this delay.

**Comment by Hazem-Ben-Khalfallah** [comment]
Hi @Fontyschriek , the version 3.9 has been submitted to Jetbrains marketplace. It will be validated within two business days.
