### ISSUE TITLE
Support for junit5

### ISSUE THREAD

**Issue by Fontyschriek** [Hazem-Ben-Khalfallah/test-cherry#4]
It would be very nice to get support for generating junit5 tests, since junit5 will be the preferred version in our ICT education (https://fontys.edu/ict/) from February 2021.
many thanks in advance.

**Comment by Hazem-Ben-Khalfallah** [comment]
@Fontyschriek a pull request has been created to add support for Junit5. This issue will be closed when the new version (**3.3**) will be available on plugins marketplace.

**Comment by Fontyschriek** [comment]
thanks for the swift response!
