### ISSUE TITLE
Add description on how to use Test Cherry in combination with generating javadoc

### ISSUE THREAD

**Issue by Fontyschriek** [Hazem-Ben-Khalfallah/test-cherry#6]
When generating javadoc from code, the javadoc tool generates errors while encountering the TestCherry tags:

> error: unknown tag: should
> error: unknown tag: verifies

This can be solved by adding the following to the javadoc commandline:
`-tag should:a:"Should:" -tag verifies:a:"Verifies:"`

In IntelliJ, this could be done by adding it at the 'Other command line arguments'
![image](https://user-images.githubusercontent.com/2254658/105058726-cf919f00-5a76-11eb-8aa5-c91c13a2e9cc.png)

Even though this is more a workaround, I think it is a good idea to add this to the TestCherry documentation (Readme.md ?), so more people can use this tool.

**Comment by Hazem-Ben-Khalfallah** [comment]
Your suggestions has been added to README file.
